import path from "node:path";
import type { Customer, Frame, Order, OrderItem, PhotoSession, Product, RetouchTask, Retoucher } from "@prisma/client";
import type { FolderPlan } from "@/types";
import { formatDate, formatMoney } from "@/lib/format";

type FullOrder = Order & {
  customer: Customer;
  session: PhotoSession;
  items: Array<
    OrderItem & {
      product: Product;
      frame: Frame | null;
      retouchTask: (RetouchTask & { assignedRetoucher: Retoucher | null }) | null;
    }
  >;
};

function safeSegment(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_")
    .slice(0, 120);
}

function toSafeRelative(value: string) {
  return value.split(path.sep).join("/");
}

function activeItems(order: FullOrder) {
  return order.items.filter((item) => item.status !== "Cancelled" && item.status !== "Inactive");
}

function retouchItems(order: FullOrder) {
  return activeItems(order).filter((item) => item.retouchType !== "None" || item.retouchNotes || item.urgent);
}

function printItems(order: FullOrder) {
  return activeItems(order).filter((item) =>
    ["print", "frame", "canvas", "album"].some((token) => `${item.product.name} ${item.product.type}`.toLowerCase().includes(token))
  );
}

function orderItemLine(item: FullOrder["items"][number]) {
  const retoucher = item.retouchTask?.assignedRetoucher?.name ?? "Unassigned";
  const frame = item.frame ? `, frame: ${item.frame.name}` : "";
  const lineTotal = (item.product.price + (item.frame?.price ?? 0)) * item.quantity;
  return [
    item.imageRef,
    `  Product: ${item.product.name}${frame}`,
    `  Size: ${item.size}`,
    `  Quantity: ${item.quantity}`,
    `  Variant: ${item.variant}`,
    `  Black and white: ${item.blackAndWhite ? "Yes" : "No"}`,
    `  Urgent: ${item.urgent ? "Yes" : "No"}`,
    `  Retouch: ${item.retouchType}`,
    `  Retoucher: ${retoucher}`,
    `  Notes: ${item.retouchNotes || item.retouchTask?.notes || "-"}`,
    `  Line total: ${formatMoney(lineTotal)}`
  ].join("\n");
}

function buildOrderSummary(order: FullOrder) {
  const itemLines = activeItems(order).map(orderItemLine).join("\n\n");
  return [
    `Order id: ${order.orderNumber}`,
    `Customer: ${order.customer.name}`,
    `Phone: ${order.customer.phone ?? "-"}`,
    `Email: ${order.customer.email ?? "-"}`,
    `Session: ${order.session.sessionType}`,
    `Photographer: ${order.session.photographer}`,
    `Session date: ${formatDate(order.session.date)}`,
    `Deadline: ${formatDate(order.deadline)}`,
    `Folder reference: ${order.session.folderPath}`,
    `Order status: ${order.status}`,
    `Payment status: ${order.paymentStatus}`,
    `Total: ${formatMoney(order.totalPrice)}`,
    "",
    "Selected images and products:",
    itemLines || "No selected images yet.",
    "",
    "Internal notes:",
    order.internalNotes || "-",
    "",
    "Customer notes:",
    order.customerNotes || "-",
    "",
    "Safety:",
    "This test summary was generated by StudioFlow MVP inside safe-test-folder/StudioFlow_Test only.",
    "No original image files are moved, deleted, or overwritten."
  ].join("\n");
}

function buildRetouchList(order: FullOrder) {
  const lines = retouchItems(order).map((item) => {
    const retoucher = item.retouchTask?.assignedRetoucher?.name ?? "Unassigned";
    const deadline = item.retouchTask?.deadline ?? order.deadline;
    return [
      item.imageRef,
      `  Retouch type: ${item.retouchType}`,
      `  Assigned retoucher: ${retoucher}`,
      `  Deadline: ${formatDate(deadline)}`,
      `  Urgent: ${item.urgent || item.retouchTask?.urgent ? "Yes" : "No"}`,
      `  Notes: ${item.retouchNotes || item.retouchTask?.notes || "-"}`
    ].join("\n");
  });

  return [
    `Retouch list for ${order.orderNumber}`,
    `Customer: ${order.customer.name}`,
    `Session: ${order.session.sessionType}`,
    `Folder reference: ${order.session.folderPath}`,
    "",
    lines.join("\n\n") || "No retouch items for this order."
  ].join("\n");
}

function buildPrintList(order: FullOrder) {
  const lines = printItems(order).map((item) => {
    const frame = item.frame ? item.frame.name : "-";
    return [
      item.imageRef,
      `  Product: ${item.product.name}`,
      `  Size: ${item.size}`,
      `  Frame: ${frame}`,
      `  Quantity: ${item.quantity}`,
      `  Variant: ${item.variant}`,
      `  Black and white: ${item.blackAndWhite ? "Yes" : "No"}`
    ].join("\n");
  });

  return [
    `Print list for ${order.orderNumber}`,
    `Customer: ${order.customer.name}`,
    `Deadline: ${formatDate(order.deadline)}`,
    "",
    lines.join("\n\n") || "No print, frame, canvas, or album items for this order."
  ].join("\n");
}

export function buildFolderPlan(order: FullOrder): FolderPlan {
  const safeRoot = path.resolve(process.cwd(), "safe-test-folder", "StudioFlow_Test");
  const year = String(order.orderDate.getFullYear());
  const orderFolder = `${safeSegment(order.orderNumber)}_${safeSegment(order.customer.name)}`;
  const relativeRoot = path.join(year, orderFolder);
  const rootFolder = path.join(safeRoot, relativeRoot);
  const folderNames = ["01_SELECTED", "02_RETOUCH", "03_READY", "04_DELIVERED"];
  const rootEntry = {
    absolutePath: rootFolder,
    relativePath: toSafeRelative(path.relative(safeRoot, rootFolder))
  };
  const subfolders = folderNames.map((folder) => {
    const absolutePath = path.join(rootFolder, folder);
    return {
      absolutePath,
      relativePath: toSafeRelative(path.relative(safeRoot, absolutePath))
    };
  });
  const folders = [rootEntry, ...subfolders];
  const fileSpecs = [
    ["order-summary", "order-summary.txt", buildOrderSummary(order)],
    ["retouch-list", "retouch-list.txt", buildRetouchList(order)],
    ["print-list", "print-list.txt", buildPrintList(order)]
  ] as const;
  const files = fileSpecs.map(([fileType, filename, content]) => {
    const absolutePath = path.join(rootFolder, filename);
    return {
      fileType,
      filename,
      absolutePath,
      relativePath: toSafeRelative(path.relative(safeRoot, absolutePath)),
      content
    };
  });

  return {
    safeRoot,
    relativeRoot: toSafeRelative(relativeRoot),
    folders,
    summaryFile: files[0].absolutePath,
    summaryContent: files[0].content,
    files,
    targetPaths: [...folders.map((folder) => folder.absolutePath), ...files.map((file) => file.absolutePath)],
    warnings: [
      "Dry-run is enabled by default.",
      "StudioFlow only creates folders and text files inside safe-test-folder/StudioFlow_Test.",
      "Existing text files are skipped and never overwritten.",
      "No image files are moved, deleted, copied, or modified.",
      "Any target outside the approved safe folder is blocked and logged."
    ]
  };
}
