import path from "node:path";
import type { Customer, Frame, Order, OrderItem, PhotoSession, Product, RetouchTask, Retoucher } from "@prisma/client";
import type { FolderPlan } from "@/types";
import { formatDate, formatMoney } from "@/lib/format";

type FullOrder = Order & {
  customer: Customer;
  session: PhotoSession;
  items: Array<
    OrderItem & {
      product: Product;
      frame: Frame | null;
      retouchTask: (RetouchTask & { assignedRetoucher: Retoucher | null }) | null;
    }
  >;
};

function safeSegment(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_");
}

export function buildFolderPlan(order: FullOrder): FolderPlan {
  const safeRoot = path.join(process.cwd(), "safe-test-folder", "StudioFlow_Test");
  const year = String(order.orderDate.getFullYear());
  const orderFolder = `${safeSegment(order.orderNumber)}_${safeSegment(order.customer.name)}`;
  const relativeRoot = path.join(year, orderFolder);
  const folders = ["01_SELECTED", "02_RETOUCH", "03_READY", "04_DELIVERED"].map((folder) =>
    path.join(safeRoot, relativeRoot, folder)
  );
  const summaryFile = path.join(safeRoot, relativeRoot, "order-summary.txt");

  const itemLines = order.items
    .map((item) => {
      const retoucher = item.retouchTask?.assignedRetoucher?.name ?? "Unassigned";
      const frame = item.frame ? `, frame: ${item.frame.name}` : "";
      return [
        item.imageRef,
        `  Product: ${item.product.name}${frame}`,
        `  Quantity: ${item.quantity}`,
        `  Variant: ${item.variant}`,
        `  Retouch: ${item.retouchType}`,
        `  Retoucher: ${retoucher}`,
        `  Notes: ${item.retouchNotes || "-"}`
      ].join("\n");
    })
    .join("\n\n");

  const summaryContent = [
    `Order id: ${order.orderNumber}`,
    `Customer: ${order.customer.name}`,
    `Phone: ${order.customer.phone ?? "-"}`,
    `Email: ${order.customer.email ?? "-"}`,
    `Session: ${order.session.sessionType}`,
    `Deadline: ${formatDate(order.deadline)}`,
    `Total: ${formatMoney(order.totalPrice)}`,
    "",
    "Selected images and products:",
    itemLines || "No selected images yet.",
    "",
    "Safety:",
    "This test summary was generated by StudioFlow MVP inside safe-test-folder only.",
    "No original image files are moved, deleted, or overwritten."
  ].join("\n");

  return {
    safeRoot,
    relativeRoot,
    folders,
    summaryFile,
    summaryContent,
    warnings: [
      "Dry-run is enabled by default.",
      "The MVP only creates folders inside safe-test-folder/StudioFlow_Test.",
      "Existing order-summary.txt files are never overwritten.",
      "No real image files are moved or deleted."
    ]
  };
}
