import fs from "node:fs/promises";
import path from "node:path";
import { PrismaClient } from "@prisma/client";

const dbPath = path.join(process.cwd(), "prisma", "dev.db");

const schemaSql = `
CREATE TABLE "Studio" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "country" TEXT NOT NULL DEFAULT 'DK', "timezone" TEXT NOT NULL DEFAULT 'Europe/Copenhagen', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "StudioLocation" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT, "defaultFolderPath" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "StudioLocation_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "authProviderId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
CREATE TABLE "Role" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT, "name" TEXT NOT NULL, "description" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Role_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Permission" ("id" TEXT NOT NULL PRIMARY KEY, "key" TEXT NOT NULL, "label" TEXT NOT NULL);
CREATE TABLE "RolePermission" ("roleId" TEXT NOT NULL, "permissionId" TEXT NOT NULL, CONSTRAINT "RolePermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "RolePermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("roleId", "permissionId"));
CREATE TABLE "StudioMember" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "userId" TEXT NOT NULL, "roleId" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "StudioMember_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "StudioMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "StudioMember_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "StudioSettings" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "orderIdFormat" TEXT NOT NULL, "defaultFolderPath" TEXT NOT NULL, "folderNamingFormat" TEXT NOT NULL, "workflowStatusesJson" TEXT NOT NULL, "sessionTypesJson" TEXT NOT NULL DEFAULT '["Family shoot","Passport photo","Portrait","Wedding","Product photo","School photo","Other"]', "retouchTypesJson" TEXT NOT NULL, "photographersJson" TEXT NOT NULL, "captureTool" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "StudioSettings_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Customer" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT, "email" TEXT, "notes" TEXT, "consentStatus" TEXT NOT NULL DEFAULT 'Unknown', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Customer_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "PhotoSession" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "locationId" TEXT, "photographerUserId" TEXT, "sessionType" TEXT NOT NULL, "photographer" TEXT NOT NULL, "date" DATETIME NOT NULL, "folderPath" TEXT NOT NULL, "notes" TEXT, "status" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "PhotoSession_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "PhotoSession_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "PhotoSession_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "StudioLocation" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "PhotoSession_photographerUserId_fkey" FOREIGN KEY ("photographerUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "SessionImageReference" ("id" TEXT NOT NULL PRIMARY KEY, "sessionId" TEXT NOT NULL, "imageRef" TEXT NOT NULL, "localPath" TEXT, "rating" INTEGER, "selected" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SessionImageReference_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PhotoSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "OrderStatus" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL, "color" TEXT, "isFinal" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "OrderStatus_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Order" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "sessionId" TEXT NOT NULL, "customerId" TEXT NOT NULL, "statusId" TEXT, "orderNumber" TEXT NOT NULL, "orderDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "deadline" DATETIME, "status" TEXT NOT NULL, "paymentStatus" TEXT NOT NULL, "totalPrice" INTEGER NOT NULL DEFAULT 0, "internalNotes" TEXT, "customerNotes" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Order_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Order_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "PhotoSession" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Order_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Order_statusId_fkey" FOREIGN KEY ("statusId") REFERENCES "OrderStatus" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "Product" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "price" INTEGER NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "sizeOptionsJson" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Product_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Frame" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "size" TEXT NOT NULL, "color" TEXT NOT NULL, "price" INTEGER NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Frame_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "OrderItem" ("id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "imageRef" TEXT NOT NULL, "productId" TEXT NOT NULL, "frameId" TEXT, "quantity" INTEGER NOT NULL, "size" TEXT NOT NULL, "variant" TEXT NOT NULL, "retouchType" TEXT NOT NULL, "retouchNotes" TEXT, "urgent" BOOLEAN NOT NULL DEFAULT false, "blackAndWhite" BOOLEAN NOT NULL DEFAULT false, "status" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "OrderItem_frameId_fkey" FOREIGN KEY ("frameId") REFERENCES "Frame" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "Retoucher" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "phone" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "notes" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "Retoucher_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "RetouchTask" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "orderItemId" TEXT NOT NULL, "assignedRetoucherId" TEXT, "retouchType" TEXT NOT NULL, "notes" TEXT, "deadline" DATETIME, "status" TEXT NOT NULL, "urgent" BOOLEAN NOT NULL DEFAULT false, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "RetouchTask_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "RetouchTask_orderItemId_fkey" FOREIGN KEY ("orderItemId") REFERENCES "OrderItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "RetouchTask_assignedRetoucherId_fkey" FOREIGN KEY ("assignedRetoucherId") REFERENCES "Retoucher" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "ProductionTask" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "orderId" TEXT NOT NULL, "assignedUserId" TEXT, "type" TEXT NOT NULL, "status" TEXT NOT NULL, "deadline" DATETIME, "notes" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "ProductionTask_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "ProductionTask_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "ProductionTask_assignedUserId_fkey" FOREIGN KEY ("assignedUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "EmailTemplate" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "name" TEXT NOT NULL, "type" TEXT NOT NULL, "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "EmailTemplate_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "EmailLog" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "orderId" TEXT, "templateId" TEXT, "toEmail" TEXT, "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "status" TEXT NOT NULL, "errorMessage" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "sentAt" DATETIME, CONSTRAINT "EmailLog_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "EmailLog_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "EmailLog_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "EmailTemplate" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "BridgeAgent" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "locationId" TEXT, "name" TEXT NOT NULL, "deviceId" TEXT NOT NULL, "status" TEXT NOT NULL, "lastSeenAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "BridgeAgent_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BridgeAgent_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "StudioLocation" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "BridgeJob" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "bridgeAgentId" TEXT, "orderId" TEXT, "requestedByUserId" TEXT, "type" TEXT NOT NULL, "dryRun" BOOLEAN NOT NULL DEFAULT true, "status" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "BridgeJob_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BridgeJob_bridgeAgentId_fkey" FOREIGN KEY ("bridgeAgentId") REFERENCES "BridgeAgent" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "BridgeJob_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "BridgeJob_requestedByUserId_fkey" FOREIGN KEY ("requestedByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "BridgeLog" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "bridgeJobId" TEXT, "action" TEXT NOT NULL, "status" TEXT NOT NULL, "message" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BridgeLog_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "BridgeLog_bridgeJobId_fkey" FOREIGN KEY ("bridgeJobId") REFERENCES "BridgeJob" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "GeneratedFile" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "orderId" TEXT, "bridgeJobId" TEXT, "fileType" TEXT NOT NULL, "path" TEXT NOT NULL, "checksum" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "GeneratedFile_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "GeneratedFile_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "GeneratedFile_bridgeJobId_fkey" FOREIGN KEY ("bridgeJobId") REFERENCES "BridgeJob" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "Activity" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "message" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Activity_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "SubscriptionPlan" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "priceDkk" INTEGER NOT NULL, "billingInterval" TEXT NOT NULL DEFAULT 'month', "description" TEXT NOT NULL, "featuresJson" TEXT NOT NULL, "orderLimit" INTEGER, "bridgeAutomation" BOOLEAN NOT NULL DEFAULT false, "userLimit" INTEGER NOT NULL, "sortOrder" INTEGER NOT NULL);
CREATE TABLE "StudioSubscription" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "planId" TEXT NOT NULL, "status" TEXT NOT NULL, "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "trialEndsAt" DATETIME, "renewsAt" DATETIME, CONSTRAINT "StudioSubscription_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "StudioSubscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "SubscriptionPlan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "PaymentCustomer" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerCustomerId" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, CONSTRAINT "PaymentCustomer_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE "Invoice" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "subscriptionId" TEXT, "providerInvoiceId" TEXT, "amount" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'DKK', "status" TEXT NOT NULL, "issuedAt" DATETIME, "paidAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Invoice_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Invoice_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "StudioSubscription" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "PaymentEvent" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT, "provider" TEXT NOT NULL, "eventType" TEXT NOT NULL, "externalId" TEXT NOT NULL, "payloadJson" TEXT, "processedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentEvent_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "userId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "metadataJson" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "DataExport" ("id" TEXT NOT NULL PRIMARY KEY, "studioId" TEXT NOT NULL, "requestedByUserId" TEXT, "status" TEXT NOT NULL, "filePath" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME, CONSTRAINT "DataExport_studioId_fkey" FOREIGN KEY ("studioId") REFERENCES "Studio" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "DataExport_requestedByUserId_fkey" FOREIGN KEY ("requestedByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "Studio_slug_key" ON "Studio"("slug");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_authProviderId_key" ON "User"("authProviderId");
CREATE UNIQUE INDEX "StudioMember_studioId_userId_key" ON "StudioMember"("studioId", "userId");
CREATE UNIQUE INDEX "Role_studioId_name_key" ON "Role"("studioId", "name");
CREATE UNIQUE INDEX "Permission_key_key" ON "Permission"("key");
CREATE UNIQUE INDEX "StudioSettings_studioId_key" ON "StudioSettings"("studioId");
CREATE UNIQUE INDEX "OrderStatus_studioId_name_key" ON "OrderStatus"("studioId", "name");
CREATE UNIQUE INDEX "Order_orderNumber_key" ON "Order"("orderNumber");
CREATE UNIQUE INDEX "RetouchTask_orderItemId_key" ON "RetouchTask"("orderItemId");
CREATE UNIQUE INDEX "BridgeAgent_deviceId_key" ON "BridgeAgent"("deviceId");
CREATE UNIQUE INDEX "SubscriptionPlan_name_key" ON "SubscriptionPlan"("name");
CREATE UNIQUE INDEX "StudioSubscription_studioId_key" ON "StudioSubscription"("studioId");
CREATE UNIQUE INDEX "PaymentCustomer_studioId_key" ON "PaymentCustomer"("studioId");
CREATE UNIQUE INDEX "PaymentCustomer_provider_providerCustomerId_key" ON "PaymentCustomer"("provider", "providerCustomerId");
CREATE UNIQUE INDEX "PaymentEvent_provider_externalId_key" ON "PaymentEvent"("provider", "externalId");
`;

async function main() {
  await fs.mkdir(path.dirname(dbPath), { recursive: true });
  await fs.rm(dbPath, { force: true });

  const prisma = new PrismaClient();
  try {
    for (const statement of schemaSql.split(/;\s*\n/).map((part) => part.trim()).filter(Boolean)) {
      await prisma.$executeRawUnsafe(`${statement};`);
    }
    console.log(`SQLite schema initialized at ${dbPath}`);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
